---
title: "Framework details"
author: "Estelle Phillips"
date: "2023-05-22"
comments: false
toc: true
toc-expand: true
toc-depth: 3
toc-title: Framework Categories
number-sections: false
---

# Patient Experience Qualitative Data Categorisation Framework, v5

## Access to medical care & support

::: {.callout-note icon=false title="Contacting services" collapse=true}

### Contacting services

Comments relating to how easy/ hard it is to contact services. It includes understanding contact routes, and how accessible these are.



Examples: 


Positive: 'You are caring, consistent, always there on the end of a phone or email.', ' I feel I can rIng back anytIme I have a problem.', 'Well traIned staff and easy contactable.', 'Good access to staff and was able to contact when needed.', 'am confIdent that If any Issues arIse that I can rIng and they wIll be addressed.'
Mixed: 'I wasn't given a contact number. I did email the referral centre and they helped.'
Negative: 'I am begging for help with my child's behaviours, and nobody is helping me. I don't know where to go or who to contact.', 'We have struggled getting through on the mobile in the evening. We often try all the way from 6.30 to 7.30, the landline isn't always any better.', 'You could and should update the information given on the website. The telephone number given was out of date, and meant that having rung it, I then had to ring another number, which was given too quickly to take down in one go.', 'Crisis need to stop asking to phone you back when you are in crisis.'


:::

::: {.callout-note icon=false title="Appointment arrangements" collapse=true}

### Appointment arrangements

Comments (which can be quite wide ranging) relating to arrangements for appointments in terms of how frequently appointments/ check-ups/ home visits/ ongoing sessions occur, how convenient they are to attend, how long they last, how long people have to wait and punctuality of appointments, as well as cancellations. It also includes how patients have/would like to receive correspondence relating to their appointments e.g. via letter, telephone, text etc. and what it did/ they would they would like it to include.



Examples: 


Positive: 'Appointment on time', '1 1/2 hour appointment gave plenty of time for dIscussIons.', 'Good to be forewarned of vIsIt.', 'Kept to your word, rang back when you said you would.'
Negative/ wishlist: 'Long wait for the appointment.', 'Really would like appointments closer together - they are too far apart', 'With covid, not enough home visits', 'Not many appts, wanted more time', 'Longer session and face to face if possible.', 'More physio and longer physio time.', 'Offering more varied time slots to fit around work.', 'Also, bare in mind that sometimes home/CPN visits can be quite inconvenient when you have young children.', 'Later appointment as 11am to early.', 'Just do the appointments according to times given to parents as it gets frustrating whilst waiting.', 'Come and see every day. ', 'On one occasion I was not made aware that my appointment could not be kept until I arrived at the centre.', 'Communication regarding appointments.  I rang to confirm an appointment time, Thurs AM and was told it was Fri PM.  When no one turned up Fri I rang again and was told it was actually Thurs PM and that I had missed it.', 'Be more open with information about appointments.', 'You cancelled my appointment twice without telling me. It's been nearly two months and I still haven't been seen. I feel very neglected by this service.', 'Appointment details given over phone - no physical evidence/reminder which could cause problems. ', 'Be more specific with time of visit, i.e. early or late morning; early or late afternoon', 'would like to know first thing in the morning if getting physio would have like it one time a day not three time week.'

:::

::: {.callout-note icon=false title="Appointment method" collapse=true}

### Appointment method

Comments relating to the format in which appointments take place e.g. video, telephone, face-to-face etc. and if/ how patients feel about the method including whether it supports their needs.



Examples: 


Mixed: 'Sometimes the video conferences did not work, but I was happy to take the sessions by phone.' 
Negative/ wishlist: 'I think facetime appts would be better than just the phone. Sometimes hard to visualise exercise advice.', 'Due to COVID it had to be by telephone which I totally understand, face to face would have been better for me.'

:::

::: {.callout-note icon=false title="Timeliness of care" collapse=true}

### Timeliness of care

Comments relating to the availability and existence of services, how quickly people are seen, treated, gain access to healthcare professionals/ services and have care arranged. This includes waiting times, how long people wait for ambulances to arrive and delays to treatment and support.



Examples: 


Positive: 'There was little waiting time', 'Everything was arranged as soon as possible.', 'I was taken aback when my psychiatrist was able to see me a lot sooner at a time of crisis.  This had never happened before.', 'A fast response.', 'My GP sent me a card asking me to self refer to physio during Covid 19.  Received a call within 1 hour to book appointment.', ' most impressive was from arriving in the ambulance to being assessed and treated at a very fast speed', 'Time-response was within two hours of referral.'
Negative: 'Shorter waiting times for treatment, took nearly 4 weeks to get this letter.', 'I would have liked to progress to Step 4 psychology quicker. At the moment I will have to wait 18 months before my treatment with them starts', 'Treatments could commence at a faster rate.', 'Waiting time was too long (about 2 months) especially when very worrying issues (i.e. heart).', 'All my contact with the Hope Centre has left me feeling desperate and frustrated. I was referred 18 months ago and, apart from my initial assessment, have yet to have any treatment.', 'The support given came to me some 5 months after my Stroke as my recovery I believe has been delayed due to this delay.', 'Excellent care, although It perhaps came a lIttle late.', 'Ambulance could have arrived sooner.', 'A two hour waiting time has led to health problems.', 'The telephone lady said would have to wait, but saying it was a stroke should have been quicker.', 'When I first contact the service he should have been but in a higher category straight away. From 8pm till 4am his was in ex stream pain. '

:::

## Activities

::: {.callout-note icon=false title="Activities & access to fresh air" collapse=true}

### Activities & access to fresh air

Comments relating to the non-medical activities provided/ not provided (e.g. exercise, cooking, games, music, art, provision of toys in children's services etc.). Includes the range of these, how patients feel about them, how frequent they are and if/ how patients are supported to participate. This incorporates information relating to patients going outside and accessing fresh air (for example this may be for walks, exercise or cigarette smoking), if/ how patients can access outside areas and if this is facilitated by the service. 



Examples: 


Positive: 'I have been offered further education and encouraged to use the gym, which I really like.', 'I like the ward activities, they keep me busy.', 'Reading, singing, watching tv, praying.', 'Pool, cards, talking to staff and patients.', 'Activities are good, colouring, painting.', 'Lots to do.', 'I am doIng a lot of actIvItIes, walkIng and arts and craft and lIstenIng to musIc, relaxatIon classes, cookIng, exercIse, cInema and bowlIng',  'the activities keep us stimulated .', 'Play specialists came round to give us some toys when we arrived to keep her entertained for the wait.', 'Could go outdoors for cigarettes… Been able to go to shop and for walks to main hospital.', 'I like the grounds, trees and plants and a garden are really good.', 'Go out when needed to - exercise from plan.'
Negative/ wishlist: 'More music mediation', 'More activities needed for full week.', 'Get off ward more and do more social stuff.', 'I would have liked a volunteer to do the activities on the ward.', 'I have to ask when I want to have a walk.', 'Too much time when nothing is happening.', 'The craft session was very good, but needed it to be a little slower and needed more time.', 'let me play', 'would like the playroom to be open again', 'more fresh air', 'My husband is not  allowed to get outside for any fresh air. Even with an escort. At least a person in prison would be able to get outside in a yard for exercise.', 'More walks/outdoor activities.', 'Allow air breaks or smoke breaks instant.'

:::

::: {.callout-note icon=false title="Electronic entertainment" collapse=true}

### Electronic entertainment

Comments relating to services provision of and patients (and their visitors) ability to access and use Wi-Fi, internet, TV, radio and any other forms of electronic entertainment.



Examples: 


Positive: 'it was a nice distraction to have the TV on.'
Negative/ wishlist: 'Have more TV remotes for the ward.', 'There are no tv's or hospital radios any more on the ward and they could do with replacing them.', 'More access to internet.', 'Televisions wired up not working, needs sorting.', 'To be honest there was nothing, except the tv which is so high priced its on par with stealing.', 'Better WiFi.', 'A D.V.D in the room would have great as there are only a few channels on the T.V.' 

:::

## Communication & involvement

::: {.callout-note icon=false title="Unspecified communication" collapse=true}

### Unspecified communication

Thin' data that relates to communication but lacks any detail around the kind of communication being refered to.
This sub-category is intended for comments which are not specific enough to be allocated to any of the other 'Communication with patients' sub-categories. If a comment provides enough information to be mapped to one or more of the other 'Communication with patients' sub-topics it does not need to be mapped here as well.




Examples: 


Positive: 'very good communication', 'The communIcatIon was excellent made me feel confIdent', 'Communication', 'brilliant communication given throughout.'
Negative/ wishlist: 'Communication at times could have been better.', 'Improve communication.', 'No communication.', 'Much better communIcatIon wIth communIcatIon needed.', 'A little bit more communication'

:::



::: {.callout-note icon=false title="Staff listening, understanding & involving patients
" collapse=true}

### Staff listening, understanding & involving patients


Comments relating to two-way communication between staff and patients in terms of how well patients feel listened to and understood by staff, the extent to which a personalised approach is taken (i.e. being treated as an individual person rather than a number). This includes if/ how people are involved in decisions about their care and whether they have enough time to do so. It also incorporates comments about whether staff talk to/ spend time with patients and engage with them to provide company.



Examples: 


Positive:'She listened to how I felt & understood me. Because she understood she was able to provide me with care, support & techniques that were very personal to me', 'always someone to talk to.', 'Nice to have somebody popping in to chat.', ' he applies CBT intelligently and adapts it to my individual needs.', 'I really felt listened to and felt that they understood my problem.', 'Changed methods to help me understand, kInd and easy to talk to', ' Liked how the staff took time out to talk to me.', 'Treated with care and as an individual not just a patient.', 'The staff were friendly and listened to me. They made me feel as though I had an input in my care, which is really important, and can sometimes feel rare in medical care settings.', 'Because they work wIth you to fInd a Good solutIon to Issues and concerns.', ' I like my consultant and know that I am trusted by him to lead my own care.', 'I really felt listened to and felt that they understood my problem. I also feel like I was given options to help me choose the best route to fix it which was good.'
Negative/ wishlist: 'Take time out to talk to patients', 'Staff could spend more time with patients, out of the office. Have someone who works here who has the same illness and understands.', 'Concentrate more on the needs of the patients and listen more.', 'The consultant on the ward would talk over me while I was having meetings with her. She never appeared to listen to what I was saying.', ' Just wish could have spent more time with me', 'Treat patients as people, not a number. Listen to patients and make them feel heard.', 'Don't ask questions in such a patronising way. It sounds so fake like you are forcing yourself to sound interested, when really patients are just a number.', 'Listen to service users and not be so judgemental. We know how we feel not you.', 'Don't assume all older patients are stupid', 'They could have listened and taken my concerns seriously and we would have avoided the entire incident in the first place.', 'Provide someone who will listen to what you are saying not matter haw silly or bad you think it sounds.', 'Let patients be involved more in their care.', 'Invole patients about decisions.', 'Don't put service users under pressure to make choices quickly, when they aren't able to think straight and need time.'

:::



::: {.callout-note icon=false title="Information directly from staff during care" collapse=true}

### Information directly from staff during care

Relates to comments referring to information being received directly from staff. These comment typically make explicit reference to staff and/or use the terms 'answered' or 'explained'. It also includes comments around language barriers when staff are directly providing information.
The emphasis of this sub-topic is on information which needs to come from staff, which distinguishes it from the 'Staff listening, understanding & involving patients' sub-category, where the focus is on where two-way communication between patients and staff is required.



Examples: 


Positive: 'Thorough, explained everything well.', 'Procedure explained well. Communication excellent. Questions answered thoroughly.', 'Explained my care to me in a way that I could understand.', 'This is all new to me.  Any questions I ask they were there to answer them.', 'My son and I were put at ease on arrival, with all stages of the procedure explained throughout, keeping my son relaxed and calm.','The staff were very good, and gave me the information that I needed.', 'FantastIc advIce and explanatIon.', 'Everything was explained well. The nurse managed to get the surgeon back out from theatre to speak to me when I raised the fact that I still had some concerns.', 'All staff very informative'
Negative: 'Explaining better so I can understand.', 'Language barrier & bad communication.', 'I was repeating the same questions numerous times and still wasn't getting an answer.', 'But sometimes the doctors need to explain things better to you.'

:::



::: {.callout-note icon=false title="Information provision & guidance" collapse=true}

### Information provision & guidance

Comments which focus on the provision of information or advice that could be taken away to be utilised by the patient (e.g. this could be through leaflets, information sheets, webpages,  education sessions etc.)
The main distinction between this sub-category and 'Information provision from staff during care' is that the emphasis here is on reference materials and information that can be taken away, rather than the 'in the moment' information provision covered in the other sub-category.



Examples: 


Positive: 'great communication and instructions.', 'leaflets - aids to memory', 'The sessions are full of practical information and are very useful for future meal planning.', 'It has given me some ideas to make things better i.e. a weighted blanket for times of anxiety.', 'Initial visit was very helpful due to lots of information given.', 'Informative, helpful and good resource.', 'Informative session, well presented.', ‘All the Info was Good and useful.', 'ExcerIse sheets helpIng me and other thIngs to help me walk.', 'Excellent advIse for my daughter on her development.', 'FantastIc source of InformatIon', 'Gave a better InsIght to dIfferent types of needs.  Very helpful.', 'GettIng the exercIses by post wIthout vIsItIng the out patIents Is a Good way for some people.', 'Good materIal, well presented.', 'Informative, plenty of strategies to try.'
Negative/ wishlist: 'May be helpful to have the food groups on a leaflets as I wont remember.', 'Coronavirus guidance could have been clearer.', 'Email exercises to patient.', 'Clarification and information on COPD ( I've used the internet to source the information)', 'Be more explicit about what I/you can do to improve my mental condition, not just to provide leaflets - most of the content was not very relevant to me (at least not to MY perception of my condition)', 'Your website is terrible having several services maintain for different areas is inefficient and not at all beneficial to users. You could make you web portals and links much better. I was sign posted to you by my GP during a telephone consultation, due to the GP not being able to provide links, I had to seek further information directly, using the internet.', 'Increase the promotion that continence can get better even for older people.', 'More education session per week, to reduce staying time.'

:::



::: {.callout-note icon=false title="Being kept informed, clarity & consistency of information" collapse=true}

### Being kept informed, clarity & consistency of information

Comments around whether people are kept informed about their care, and whether the information recieved is clear, consistent and accurate. It includes whether care happens and progresses in line with what people were told by services.




Examples: 


Positive: 'good at keeping me informed during a difficult time.',  'Service was clear and concise. About projected plan, trajectory and outcome.', 'Been kept informed all stages of treatment', 'The good thing was that when you said you would do something you did it & when you said you would be round you was', 'We have been updated and Informed about the waItIng tImes.'
Negative/ wishlist: 'Communication from doctors and ward manager would be appreciated, as we don't feel we've had a full circle of contact only from HCAs and nurses when we ring in.', 'Communication is often contradictory, phone calls are not returned, staff do not introduce themselves and I am made to feel like a problem, when I try to clarify what is happening. Promises of treatment are made regularly but never fulfilled.', 'Not leaving us in dark', 'Could get more information about what's happening with my care. Bit vague in places.', 'Kept me in the loop more.', 'When told something I would like it to be followed through.'

:::



::: {.callout-note icon=false title="Service involvement with family/ carers" collapse=true}

### Service involvement with family/ carers

Comments relating to services involving, engaging, contacting and communicating with a patients family and/or carers. This includes whether they are listened to and the provision of support groups for them.




Examples: 


Positive: '[Name] listens to me and my wife about my condition, to me that is important, some services do not take wife's input into consideration.'. 'Good family contact.', 'You help by being there for myself & family', 'Contact made wIth patIent's wIfe. FamIly are extremely happy wIth the support and care that they receIve from the CommunIty Nurses, say that they are well cared for  by them and they communIcate well wIth them.'
Negative/ wishlist: 'Engage with carer where appropriate, as it is not always apparent from talking to the patient how serious the issues are, and it is difficult to discuss mental health issues in front of someone who has a mental illness.', 'Keep in contact with the patient & carer.', 'Bassetlaw Carer Support Group "Brilliant".'

:::



::: {.callout-note icon=false title="Patient contact with family/ carers" collapse=true}

### Patient contact with family/ carers

Comments relating to the contact that patients do/ can have with family, friends and/or carers. This includes the visiting arrangements at the service.



Examples: 


Positive: 'It has been nice to have visitors.'
Negative/ wishlist: 'Have more time off the ward with my family.', 'Not being able to have visitors during covid has been hard.', 'The chance to video call family was never offered.', 'With the current pandemic I understand it is hard to change any policies. However just having a family member being able to attend would of maybe helped.'

:::

## Environment & equipment

::: {.callout-note icon=false title="Cleanliness, tidiness & infection control" collapse=true}

### Cleanliness, tidiness & infection control

Comments relating to the cleanliness and tidiness of the environment and equipment (for example wards, rooms,  toilets, furniture). It also incorporates how timely, efficient and thorough cleaning/ maintenance staff are in addressing related issues, and the frequency of cleaning. Includes feedback on the rules to prevent the spread of infection e.g. use of PPE/ face masks, and adherence to guidelines in relation to this. 
NB: Visiting restrictions (which come up in relation to COVID infection control), are not mapped here but captured under a separate 'Patient contact with family/ carers' sub-category.



Examples: 


Positive: 'Very clean areas', 'the cleaning lady was thorough', 'Ward is well organised ,kept clean and tidy', 'Nice ward was clean and tidy. Toilets was clean and the bay in general.'
Negative: 'Cleaner ward - dirty.', 'Be more efficient cleaning wise.', 'occasional dirty toilet bowl but that's down to the last user.', 'Wiping bed tables , did this myself as was not done during my 3 day stay.', 'it was unclean & when I complained about silver fish in the bathroom was told the maintenance men wouldn't come out for them', 'Masks not effective & not worn correctly. No social distancing.', Hygiene awareness for the staff.' 

:::



::: {.callout-note icon=false title="Sensory experience" collapse=true}

### Sensory experience

Comments relating how people experience the noise, temperature, lighting, and smell of the environment:
- In relation to noise this incorporates information about noise levels (e.g. other patients, staff chatting, doors banging, equipment bleeping), how well patients can sleep and rest within the environment. 
- In relation to the temperature this includes whether it was too hot, cold, whether there were drafts etc., comments around whether the service took any actions to address temperature issues, as well as suggestions of how this could be done, e.g. through the use of air conditioning, fans etc.
- In relation to the lighting of the environment this includes whether it was too bright, dark, the appropriatness of the level of lighting etc. and issues with lighting e.g. switches, lights not working etc.
- In relation to smell this is about how the environment or equipment smells, if/how this could be addressed where there are issues



Examples: 


Positive: 'Lovely quiet little spot.  Slept better here too.', 'Because you was able to get the rest that you wanted', 'very quiet just like staying in a premier inn in a 2 bedded room', 'The atmosphere was generally calm and peaceful.', ' The ward was lovely and having a side room was amazing as it meant that I could sleep and rest without the hustle and bustle of a general ward.', 'Peaceful environment, not too hot', ' Clean and bright which helps mood.'
Negative/ wishlist: 'Less noise with doors banging.', 'Disturbed constantly during the night.', 'I would have liked my own room, as I was kept awake a lot of the nights by a peer.', 'Patients are very noisy day time, and also night time, and it's very hard to get away from it, anywhere on the ward.', 'NothIng, other than keepIng a dIsrupted patIent quIte overnIght.', 'It was too busy and noisy on the ward, not conducive to a resting atmosphere.', 'Keep the rowdy patients to an isolated ward.' 'Temperature of room wasn't good for baby but did get sorted', 'Air con as was too hot all day but, staff brought me drinks', 'Open windows.', 'Room is cold.', 'Turn the radiators off .', 'Turned the air con off. God damn, who needs air con at 3am?', 'get heater fixed in the ambulance', 'Not too bright lights when being woken up in a morning.', 'lIghts In corrIdor could be turned off at nIght', 'Light in room not working and faulty.', 'The blood pressure monitor and cuff smelt of cigarettes which was quite unpleasant. Also old perfume/aftershave. I don't know if there is any way of removing the smell in between users, but it would be an improvement.', 'There was a drain smell in my en-suite bathroom. This is my only complaint'

:::



::: {.callout-note icon=false title="Environment & facilities" collapse=true}

### Environment & facilities

This is a wide ranging sub-topic which captures generic comments about the environment ('thin' data that relates to the environment/ facilities but lacks any detail), layout, comfort, whether the environment allows privacy to be maintained, decoration, maintenance and upkeep: 
	- In relation to comfort this includes information relating to the size of rooms, how busy areas are and how many people are in them, the availability and physical comfort of the surroundings, furniture (i.e. beds and chairs) and bedding. 
	- In relation to the atmosphere of the environment there is likely to be explicit mention of the environment such as 'ward', 'place' etc. and how this made the patient mentally feel (e.g. happy, positive, calm, depressing etc.) and the vibe they got from their surroundings (friendly, lovely, homely etc.).
	- In relation to privacy comments cover how private the environment is, including the use of single rooms, curtains, whether conversations can be overheard and warnings when entering rooms.
	- In relation to decoration this includes how well decorated e.g. painted, carpeted the environment is, as well as comments around how well facilities are maintained, and experienced by patients e.g. whether refurbishment was needed.



Examples: 


Positive: 'Environment', 'lovely environment', environment is ok', 'ensuite facilities great', 'The facilities are very good.'
'there's a bed for me to lie down', 'Beds are very comfy…', 'The ward was clean and very comfortable.', 'Atmosphere - home from home.', 'Happy and FrIendly envIronment', 'The ward is a lovely place to get better. Make lots of friends on the ward…', 'Landing here - feel of rehabilitation from being here.', 'The atmosphere was very calming, even when it did get a little busy at times, I felt so comfortable on the ward.', 'Positive vibes.', 'friendly environment', 'Having a private room helps…', ' very private', 'It's veyr colourful and makes kids happy.', 'The room was well maintained'
Mixed: 'A few times were I needed help staff was there to help me, which is good because things can get busy in here as there's a lot of people in small space.'
Negative/ wishlist: 'not that comfortable in a chair. Bed would have been better', 'Somewhere more comfy to sit.', 'You could of given me a bed to rest on.', 'Better bed linen.', 'More seats', 'Chairs in waiting area.', 'only place to sit was the corridor, which was very busy.  A better waiting, area could have been provided.', 'Not enough room in waiting area arrived and only person in waiting room, then 20 others arrived', 'The reception bit could be made bigger', 'Only the chair as a bed, incredibly uncomfortable and difficult to sleep', 'There doesn't' seem to be a lot of space anywhere.', 'Where at all possible, could bed s be provided for overnight parent, rather than the recliners.As chairs, they are fine, but getting any sleep on them is impossible.', 'When you're there for a very long stay, your body ends up aching because of how poor the mattress and sofa bed quality is', 'More one to ones in private. Maybe single rooms.', 'There should be more privacy areas, as curtains provide little privacy.', 'Just to encourage 'knocking' before entering a room.', 'Reinforcing that knocking on the door and walking in without go ahead is  unacceptable. That looking into the room without prior consent shouldn't be allowed', 'Your building could do with redecorating and new carpets!', 'The walls could do with a paint'

:::



::: {.callout-note icon=false title="Safety & security" collapse=true}

### Safety & security

Comments about how safe and secure the environment is and the safe use of equipment. Includes how people are protected from harm within the environment, as well as how their belongings are protected from theft or damage.



Examples: 


Positive: 'EquIpment was ordered and delIvered very promptly as was the follow up to ensure safe usage.', ' We know patIent Is safe and secure In current settIng, away from any kInd of harm or abuse.', 'Safe environment'
Negative: 'Fire door propped open with chair.', 'Tighten security, as 3 1/2 years ago I got assaulted on the assessment ward.', 'My husband was left to fall out of his bed and fracture his hip and pelvis.', 'Keep a better check on personal possessions'

:::



::: {.callout-note icon=false title="Provision of medical equipment" collapse=true}

### Provision of medical equipment

Focuses on if/how patients are receiving the equipment that they need and whether it is appropriate (e.g. medical supplies such as bandages, pads, machines, mobility aids etc). Incorporates how quickly such equipment is received. 



Examples: 


Positive: 'Hosiery ordered asap.', 'Sorted pads out for my Mum.', 'Prompt delivery of equipment.', 'grab raIls fItted very excellent servIce', 'They were very helpful In gettIng equIpment that was needed to stay at home.', 'Also arranged all mothers waking and bathing aids.'
Negative/ wishlist: 'Making sure enough of correct dressings in the home.', 'Improve the supply chain of bandages. There is frequently an issue about having the necessary bandages. The nurses on the front line always resolve this, but they would be assisted by a better supply chain.', 'I needed a new machine to take back to [Service name] and there was a delay in staff at [Service name] having training. This made my stay in hospital longer than expected. The ward managed to arrange this so I could go home quickly'

:::

## Food & diet

::: {.callout-note icon=false title="Food & drink provision & facilities" collapse=true}

### Food & drink provision & facilities

Includes food quality, taste, temperature, choice, variety, suitability, nutritional value, times of provision and help with eating, as well as the provision of equipment & facilities (including kitchens, vending machines & shops) for patients & visitors to prepare or access food beyond that provided directly by the service.



Examples: 


Positive: 'Good food', 'food been good and plenty to chose from', 'my grandad asked for more food you sed yes and it made him very happy and I loved the ham sandwiches', 'food was good water is clean', 'Take aways', 'Great facilities to hydrate and feed parents too'
Negative/ wishlist: 'food got very repetItIve  a varIatIon would of been nIce', 'As a diabetic the high carb food was a disaster', 'Food Is the maIn problem, not enough fresh fruIt, better salads. CurrIes are the best optIon but could be made more authentIc eg, nans and chutneys.', 'Meals should be served hot.', 'Quite often patient missed lunch or supper as wasn't asked', 'Meals need to be ward/patient treatment specific.', 'Only having use of one hand, food cut up eg potato's cut, but meat not.  Toast buttered but not maraladed, so having to call someone to help.', 'Home cooked food truly boosted my morale, but with out access to a microwave, this seemed quite tricky.', 'the confectionary machines could have been nearer to the patients for a treat', 'Egg and bacon for breakfast lol', 'Perhaps offer lighter meal alternatives.'
Mixed or neutral: 'Food varies - sometimes good and sometimes not.', 'Food is fair to (only one chips not quite cooked)', 'Its hard with food as everyone is different', 


:::

## General

::: {.callout-note icon=false title="Gratitude/ good experience" collapse=true}

### Gratitude/ good experience

Thin' data highlighting an overarching positive sentiment and satisfaction around their experience, including that no improvements are needed/ were identified.
This sub-category is intended for very generic comments, with the exception of 'Non-specific praise for staff' if any other topics can be applied then gratitude does not need to be used as well. This way this topic will be restricted to comments where there is no additional analytical value in looking at the comment qualitatively.



Examples: 


‘All good’, ‘Perfect.’, ‘Very pleased with the service received.’, ‘Thank you’, ‘Very good’, ‘Care was fantastic!’, ‘Cannot think how you could do any better’, ‘Nothing’, ‘Absolutely no problems’, ‘Nothing I was entirely happy with my experience during my stay’, ‘Absolutely nothing, you do an ace job.’, ‘NothIng It was all Good thank-you’.

:::



::: {.callout-note icon=false title="Negative experience" collapse=true}

### Negative experience

Thin' data highlighting an overarching negative sentiment or dissatisfaction around their experience.



Examples: 


‘Most things.’, ‘Everything’, ‘Everything, your a joke.’

:::



::: {.callout-note icon=false title="Not assigned" collapse=true}

### Not assigned

Information which is not relevant to any of the other sub-categories, including information that is unclear and lacking in any context to categorise what it is about.



Examples: 


Have more respiratory patients.', 'n/a', 'Rama.', 'I recommend 'same standard'', 'Lots with more patients', ' Wearing a baby grow could be doing development.'

:::



::: {.callout-note icon=false title="Organisation & efficiency" collapse=true}

### Organisation & efficiency

Thin data which references how efficient, well-led or organised the service is, without drawing out any specifics. 
This sub-category is intended for very generic comments which do not provide detail, for example they say 'efficient', but with no indication of what/who is efficient, where further detail is provided e.g. 'Staff are efficient' or 'Efficient appointments' should be mapped to the relevant staff or appointment sub-categories, rather than here.



Examples: 


Positive: 'Always very efficient.', 'Well organised.', 'Very helpful, efficient  service.', 'well run facility', 'Very organised dept.', 'Quick and easy.', 'Always quick and efficient.', 'Straight forward.', 'Everything smooth running'
Negative: 'Get things done.' 

:::



::: {.callout-note icon=false title="Funding & use of financial resources" collapse=true}

### Funding & use of financial resources

High level comments around the amount of funding the service receives or needs, and how the service are utilising their financial resources.



Examples: 


Negative: 'More Govt. funding to help you do your job better', 'Ya give them more money they deserve it.', 'Make resources too alleviate pressure and prevent good staff from leaving or losing love for their job.', 'If you received more funding, or made better use of the funding already available to you (e.g. by reducing bureaucracy & management, if applicable) more help could be provided to people.'

:::



::: {.callout-note icon=false title="Collecting patients feedback" collapse=true}

### Collecting patients feedback

Feedback and views on how this data was captured and used e.g. design of the FFT questions, data capture method, ease to complete, whether they know which service it pertains to and the value of it etc. Also incorporates comments where respondents say they have filled the form in incorrectly or are generally talking about how they have filled in the form.




Examples: 


Negative: 'I have had several appointments with several dept so unsure as to what service you are pertaining too', 'I think this form is a disgrace'., 'Because despite referring in March 2022 we have had no contact at all from anyone and it is now the end of May 2022. Ive no idea why you sent the feedback message when we dont yet have any service to feedback on', 'Not sure what appointment this is for so I gave the best answer I could for a general opinion', 'Change the questions ', 'Who am I talking to? | I have answered several surveys and dont know which one you are'
Neutral: 'Sorry I made a mistake. I meant to put 1.', 'Continued comments for 2 question on form.'

:::

## Medication

::: {.callout-note icon=false title="Supplying & understanding medication" collapse=true}

### Supplying & understanding medication

Comments (which can be quite wide ranging) relating to medication processes and how the patient experiences these. Includes comments about missed doses, titration, waits to receive meds including at the pharmacy, which medications are prescribed, appropriateness of medication and medication reviews, the receipt of information and patients knowledge around their medication (e.g. why they are taking it, why it is being suggested, the side effects, when and how to take it, changes to it etc.)



Examples: 


Positive: 'a few days In the dogged determInatIon of a nurse to get the meds prescrIbed properly', 'medication prescribing was good', 'Wrote medications promptly.', 'During the enforced switch from Phenelzine to Isocarboxazid over this summer, which resulted in a relapse into depression for a couple of months, both Dr [Name] and [Name] were unfailingly supportive and helped me to make the change successfully.', 'Yes you told me what the medication was for, how much to take, when to take it, and how it might make me feel.', 'Dr has helped chIld a lot, her calm manner and explanatIons to chIld In such a way that they understand theIr meds have helped hIm.'
Negative/ wishlist: 'They didn't give out medication when they should as they didn't have it for 2 doses.', 'Sadly there is a strong reliance on medication and some medication can interfere quite strongly with your daily life i.e. due to the side effects like blurred vision. ', 'Have now called twice to request a medication review (as I was told to), with no response other than that a message will be given to the Dr.', 'All is good except, waiting on meds at weekend, when all week you have it at a curtain time, then weekend it goes 'pete tong'.', 'It has now been 6 months I have been waiting for my prescription, but I feel like I can't keep reminding the service that I am waiting, as I don't want to look like a drug addict.', 'The pharmacy is to slow', 'Sometimes things seem to get missed in handovers and have had to ask for meds etc. Timing of meds late at night not appropriate for children.', 'Providing a gap between medication and meals.', 'We would like to know decisions in regards to medication changes', 'Let me know why medication stops and starts.', 'Letting me know what my meds are'

:::


::: {.callout-note icon=false title="Pain management" collapse=true}

### Pain management

Comments relating to if and how pain relief is supplied. Includes whether patients pain is addressed in a timely, and effective way which meets their needs.




Examples: 


Positive: 'Because everyone paid attention to me and provided pain relief in a timely manner', 'Because I was well looked after, and made pain free', 'Managed my pain when I needed it.'
Negative: 'I have been in pain for the last 7 weeks with my back.  I have not had no pain relief and have not seen a doctor or anyone else to get some pain relief! I am still in pain.', 'Got rid of pain patch and pain for me, but don't think the tablets that replace the patch are strong enough to get me through the day.', 'Keep on top of pain relief, as there were times I had to ask for it.', 'Pain relief sometimes took time as nurses busy.'

:::

## Mental health specifics

::: {.callout-note icon=false title="Mental Health Act" collapse=true}

### Mental Health Act

Comments about peoples views and experiences of care in relation to the Mental Health Act. This includes detention (i.e. being sectioned), leave, restrictions and rules, access to items and release. 



Examples: 


Positive: 'Staff helped with my release & resettlement'
Negative/ wishlist: 'Would like to have been able to use escorted leave more.', 'Stop keeping us locked up over 23hrs a day, doing damage to everyone's mental health.  We will all be basket cases before much longer.', 'Management making more restrictions and making Rampton worse every year. ', 'More time on leave.', 'The staff are helpful and friendly, but I want to go home I don't need to be here.', 'Offer more group community leave, like days outs.', 'Release.', 'Not lock people up who are not ill.', 'Some patients were allowed phone charger and others not.', 'Bound by rules being in a medium secure, flouting the rules as a patients, as a patient observing lower tier staff doing the same sometime doing as they please, is a little annoying.'

:::

## Patient journey & service coordination

::: {.callout-note icon=false title="Diagnosis & triage" collapse=true}

### Diagnosis & triage

Comments relating to diagnostic and triage processes. In relation to diagnosis this includes the use diagnostic tests/ assessments, how patients feel about the process used/ not used to identify health issues and decisions made by health professionals around diagnosis. In relation to triage this includes comments relating to the appropriateness of the lines of questioning used by staff, for example 111 call handlers or receptionists, and the appropriateness of decisions made based on answers given. 



Examples: 


Positive: 'The way that the questions drilled down the problem I had and advice given.', 'Decision by Medic at clinic to send to hospital quickly taken and proved correct.'
Mixed: 'had to answer scripted questions which we felt were not relevant. The outcome was good, however, as a First Responder was called and arrived within a couple of minutes '
Negative: 'I feel I should have had an MRI scan or lumber puncture to confirm diagnosis, which I feel is still not definite. I feel I am on death row.', 'My psychiatrist refuses to refer me for an autism assessment based on being able to make eye contact. Despite my son's autism paediatrician suggesting it strongly.', 'HavIng all relevant tests  done earlIer. to get the approprIate started.', An X-ray while I was here to ease the stress of the further time delay in diagnosis.','The first call handler was good but she obviously had to ask lots of irrelevant questions.', 'The operator was great but unfortunately the questions I had to answer required an ambulance for myself.  I refused. I had a bad back , not a fall or broken back', 'Some of the questions asked to resolve my problem seem unnecessary for my health emergency'

:::



::: {.callout-note icon=false title="Referals & continuity of care" collapse=true}

### Referals & continuity of care

Comments relating to referals, how well services are integrated and communicate with each other (e.g. the sharing of records, healthcare professionals knowledge of other services etc.). It also encorporates patient experiences around continuity of care and how smooth this is (i.e. in terms of negative experiences this can include descriptions of being lost in the system, falling between gaps, having to chase services themselves during transitions, for example from children to adult services etc.) 



Examples: 


Positive: 'Getting in touch with health professionals such as my doctor to get stuff sorted quickly.'
Negative/ wishlist: 'The original referral from my GP took longer than expected, because the service had moved offices, so it went to the wrong place.', 'Contact between hospItal and GP seemed to be lackIng.', 'Feedback to referrer accurately, and promptly giving an update. Improve communication between primary secondary care.', 'It took me 6-7 months to get the Manor Road team to refer me into the service, despite the SDS being ready to take me on as soon as they'd received the referral, because the psychiatrists I saw during that time had never heard of it and couldn't be bothered to find out more.', ‘I was referred 18 months ago and, apart from my initial assessment, have yet to have any treatment... During this telephone call I was told that the doctor was going to chase up my treatment... She warned me that I may get lost in the system though.', ‘My 17 year old son was told that as he was turning 18 soon there was no point in offering him any treatment after a suicide attempt. He would have to wait until he was 18 and then get in touch with the adult service.', 'in the document it provided me with next steps I could take, but it wasn't very clear in my opinion what I was supposed to do next, as it pointed me towards three different NHS therapy groups that all seemed very similar. It was difficult for me to know what to do, and I wish it was a bit smoother if possible.’ 

:::



::: {.callout-note icon=false title="Length of stay/ duration of care" collapse=true}

### Length of stay/ duration of care

Comments relating to how long people spent in hospital and/ or receiving care, including whether they  felt that this was too short or long.



Examples: 


Positive: 'All helped me to get home as soon as possible, I just wanted my own bed', 'From arrival to discharge I was not hanging around all nurses and doctors listen and did what they could to ease my symptoms'
Negative/ wishlist: 'Maybe look at reducing patient's stay in hosptial', 'Wish it was a longer service.', 'Service too short.'

:::



::: {.callout-note icon=false title="Discharge" collapse=true}

### Discharge

Comments relating to discharge processes and peoples experiences of care ending at a particular service. This includes how quick discharge took, whether people felt ready to be discharged, as well as if sufficient plans, support and further care are put into place when leaving a service.



Examples: 


Positive: 'On discharge I had a clear plan and felt more optimistic about going forward than I have in a long time.'
Negative/ wishlist: 'When you leave... jeez! Like you leave and they say oh we've made sure you have this, this and this support. But as soon as you walk out those doors. You have nobody! And then they blame it on you.', 'Discharger quicker.', 'Don't discharge patients leaving them in a worse state than before your involvement.', 'Perhaps some warning about going home.  I thought I was staying another day but went home quite quickly which was fine, just a surprise.', 'Better support with mental health when leaving', 'You discharge service users too early so they end up being referred back to you in a worse way meaning more support needed.', 'Better and quicker communication to referrer when a patient has been discharged out of your care.', 'Improve the discharge process.', 'Quicker discharge, waiting round for medication.', 'Someone to give advice about aftercare before leaving.'

:::



::: {.callout-note icon=false title="Care plans" collapse=true}

### Care plans

Comments making specific reference to whether patients have care/ treatment/ action plans in place and any views and experiences that people have in relation to their plans (e.g. whether they are/were sufficient, appropriate, actioned etc.).



Examples: 


Positive: 'The interaction and the detail gone into and the help to build an action plan for my own health and diabetes management.', 'Could not fault thIs care plan.'' 'including me with a daily care planning'
Negative: 'there are still some underlying anxiety issues & I don't feel we have properly addressed these. It would have been good to have come up with an action plan for next steps / recommendations re: how could address these', To carry out plan of care as discussed.', 'My condition of borderline is not taken seriously and a proper treatment plan was not given.'

:::



::: {.callout-note icon=false title="Patient records" collapse=true}

### Patient records

Comments relating to records and paperwork about the patient and their care. This includes the accuracy, protection and confidentiality of personal information. It also incorporates peoples experiences of supplying their information (e.g. whether they understand their records/ paperwork, how it will be stored and used, what is being signed and why).




Examples: 


Positive: 'clear InstructIons and follow up paperwork'
Negative: 'Record information accurately. Get the patient's name right on letters. Learn how to spell medical conditions correctly in letters.', 'Not talk about patients past with other staff and our history and not to breach our confidentiality by passing on information to other third parties.', 'The carers assessment form is too long - hopefully its not a strategy to keep people from applying.', 'They made him sign paper work he did not understand.'

:::



::: {.callout-note icon=false title="Impact of treatment/ care" collapse=true}

### Impact of treatment/ care

Comments which refer to how successful treatment and care has been in improving the patients health, including outcomes and the impact that this had had on their life where stated. This can relate to physical and/ or mental health and be about positive or negative impacts.



Examples: 


Positive: 'Because wIthout the team I don't thInk I would be here.', 'HavIng support of crIsIs team for 6-8 weeks had a bIg Impact and helped Greatly.', 'They guided me through a tough patch.', 'Feel the help I get is making a difference to my recovery', 'Helping me heal my wound and getting my independence back.', 'Make my breathing much better so I go out with my family.', 'Treatment was very good at getting rid of my hepatitis C.','I'm stIll gettIng paIn but not as bad.', 'After 12 weeks of excellent advIse and InformatIon on healthy eatIng and lIfe style changes and excellent exersIce advIse . I have managed to lower my blood sugar levels', 'I came into hospital suicidal, spoke to your team and went home hopeful & still coping.', 'I'm upset to lose my therapist, so know that she made an impression on my life. Helped me be more mindful of other people and their intentions.', 'Making me feel alive again.', 'The therapy has made me feel so much more positive.  It has made me feel motivated.', 'Building my son's confidence.'
Negative/ wishlist:  'I wouldn't use this service again. Don't feel like it helped me at all','Wouldn't use this team again or recommend you to anyone, as it's not worth the hassle and stress, to be left feeling worse than I was prior to contacting you.', 'First appointment was phone, exercise recommended made pain worse. Eventually face to face appointment, another exercise made pain worse.' 

:::



::: {.callout-note icon=false title="Links with non-NHS organisations" collapse=true}

### Links with non-NHS organisations

Comments about how the NHS works with external organisations or groups (e.g. social care, community groups, councils etc.). This includes signposting, help and advice around how to access financial assistance or benefits.



Examples: 


Negative/wishlist: 'Improve connection to community and community services.', 'Communication between healthcare & home office.', 'Better join up with social services.' , 'Extra money in personal benefits to help and encourage our mental wellbeing, to give us hope and do things we cannot afford to do on such low personal benefits, to help us believe we want to live and can afford things.', 'Didnt help me to fill a form of DLA/PIP', 'I was asked to voluntary go to into mental health unit- as they would help me to talk n work through my problems, and they would help with accommodation and help with benefits BUT all has happened is Im given drugs to calm my mood and keep me locked up..'

:::

## Service location, travel & transport

::: {.callout-note icon=false title="Service location" collapse=true}

### Service location

Comments relating to the geographical location of services, distance required to travel, locations (e.g. specific hospitals, towns, cities) where patients would/ wouldn't like to receive care and the convenience of the site of service provision. Also incorporates ability to find the service e.g. provision of directions.



Examples: 


Positive: 'GlenfIeld was a Great local hospItal- as nearer to home.', 'it was brilliant that I could go to my local surgery instead of having to go to the hospital'
Wishlist: 'Have surgery nearer my home', 'Only complaInt Is that I live near Loughborough so that would have been my preferred choIce because of vIsItIng.', 'Same service available at Bingham Health Centre.', 'Let me stay here instead of moving to another place.', 'Put a map showing location of service. Cotgrave Hub is hard to find as postcode does not match google maps.'

:::



::: {.callout-note icon=false title="Transport to/ from services" collapse=true}

### Transport to/ from services

Comments relating to the transportation required to get to/ from services, arrangements around this and the quality of the service provided (e.g. comfort, appropriateness, suitability and maintenance and availability of vehicles, help getting into transport, quality of driving, routes taken) . This incorporates both hospital provided transport, including the use of taxis and public transport. 
NB: Ambulance service comments relating to ambulance response times should be mapped to 'Timeliness of care', rather than here. 



Examples: 


Positive: 'Arranged transport', 'Nothing. Everything 1st class. Excellent safe drivers and so helpful in every way.', 'No problems - an interesting pleasant journey both ways.'
Mixed/ neutral: 'I could not have travelled to hospital by any other means due to self isolation. No taxis, no public transport, no self drive.', I waited 4 hrs from the discharge centre but with Covid restrictions only I person per vehicle.'
Negative: 'All ok except no transport home- I have had it in the past', ' 'Other than giving all the drivers bigger cars, not a lot.', 'The taxi drivers do not help getting in and out of car.', 'The vehicle had a harsh ride and was [unreadable] and therefore very noisy.', 'I was advised to make my own way to hospital despite having a heart rate over 180 beats per minute and breathlessness.', 'The ambulance has terrible suspension as to be uncomfortable', 'The one time I had taxi to pick me up I had to wait hour and half in cold draughty doorway. Then he wasn't very helpful.', 'Sometime transport not coming on time.', 'Waiting time. It took 4 hours to get transport home.'

:::



::: {.callout-note icon=false title="Parking" collapse=true}

### Parking

Comments relating to the parking of personal vehicles when using services e.g. availability of spaces, location of disabled bays, cost etc.



Examples: 


Negative: 'Not much parking available a the relevant area.', 'Put back the disabled parking bays outside the transplant clinic!', 'getting into car parks was horrendous today - disabled badge made no difference - turned away and told to go outside of hospital.', 'I was turned away from parking in the main car park even though there was 5 empty disabled bays.'

:::

## Staff

::: {.callout-note icon=false title="Non-specific praise for staff" collapse=true}

### Non-specific praise for staff

Thin' data highlighting an overarching positive sentiment and satisfaction with staff, rather than drawing out any specifics (e.g. the data doesn't go into which personal attributes staff display, just uses generic terms such as 'great', 'good', 'brilliant', 'nice', 'exceptional', 'fabulous', 'amazing', 'wonderful', 'angels' or 'well looked after' by staff etc). 
This sub-category is intended for very generic comments, if any specifics are included (e.g. that staff are 'helpful', 'friendly', 'caring' etc.) then 'Staff manner & personal attributes' should be used, without the comment needing to be mapped here as well.




Examples: 


There is nothing better [Name] can do.', 'Nothing the staff are great.', 'Everyone was very good.', '[Name] brilliant', '[Name] & [Name] deserve pay rise.', 'The service from [Name] has been exceptional - thank you!', 'Nice Staff.', 'That [Name] is a very great nurse.', 'The staff are lovely.', 'Staff are great - including all staff.', 'The nurses were superb! XXXX has found her vocatIon!', 'A bIg thank you to staff  BrIllIant physIo!', 'All the carIng staff were absolutely fabulous.  They dId gIve Good advIce and all the help he needed to move about.  Keep up the Good work lIttle angels thanks.', 'Extremely super staff who work on thIs ward.', 'Happy wIth physIotherapIsts.', 'I love the people who work in this service, but XXXX is my favourite.', 'Look after you well.', 'The staff did their job well.', 'Amazing staff', 'Angels on this ward', 'Because I was looked after very well', 'Been well looked after', 'Because you guys are awesome', 'Everyone was wonderful', 'Fantastic service from all staff thank you all', 'Thank you to all the wonderful staff who cared for me', 'The nurses who looked after us today are angels and deserve a medal, nothing was too much trouble and made me feel at ease as a mummy thank you * and * xx', 'You were all stars.', 'You guys nailed it!'

:::



::: {.callout-note icon=false title="Non-specific dissatisfaction with staff" collapse=true}

### Non-specific dissatisfaction with staff

Thin' data highlighting an overarching negative sentiment and lack of satisfaction with staff, rather than drawing out any specifics. It also incorporates generic comments which indicate a wide variation in experiences with staff.



Examples: 


I still feel I was treated appallingly by a different team member at my first appointment which (comments finish here)', 'Staff not bothered about patients, more concerned on ipads etc.', 'Staff.', 'Nursing staff can be nice, but not all the time.', 'Reception staff some good some really awful.'

:::



::: {.callout-note icon=false title="Staff manner & personal attributes" collapse=true}

### Staff manner & personal attributes

Comments highlighting the specific attributes that staff display in interacting with patients, how patients experience these and perceive staff, the manner in which they are treated by staff, including staff attitude. It incorporates descriptions of staff as 'friendly', 'helpful', 'caring', 'kind', 'professional', 'polite', 'efficient', 'supportive', 'attentive' and whether people felt that they were treated with dignity, respect and empathy by staff, as well as whether staff displayed teamwork.






Examples: 


Positive: 'The staff do care about the patients.', 'All staff friendly and helpful.', 'nurse very friendly, kind, polite and job done well', 'Nice keyworker - supportive.', 'Polite, professional, caring', 'Being treated with respect & kindness.', 'All staff were FrIendly and carIng and treated the patIent wIth dIgnIty and respect.', 'The staff were professional and yet approachable at all times, friendly and understanding and yet still letting you keep your dignity.'
Mixed: '90% of staff were fantastic, helpful and supportive Small minority the opposite.', 'We spoke to 3 members of the team. The first 2 were extremely rude, the 3rd gentleman was much more kind.'
Negative: 'A few members of staff could do with more training on compassion, bedside manners', 'Be professional, kind and supportive. The doctor who dealt with us was none of these things.', 'Improvement in attitudes as not everyone here is faking it', 'Overnight staff didn't introduce themselves.', 'Teach staff empathy. I left feeling suicidal because of the treatment I received from staff on ward [Name]'


:::



::: {.callout-note icon=false title="Number & deployment of staff" collapse=true}

### Number & deployment of staff

Focusses on comments which explicitly reference the number of staff (staffing levels, shortages, too many, a lot, not enough etc.). It includes views and experiences around how staff are deployed and their skills mix (seniority, job role etc.), as well as references to the demographic make-up of staff (e.g. gender). It also incorporates comments around staff leave and recruitment.




Examples: 


Positive: 'Lots of staff', 'plenty of members of staff who are working extremely hard to give excellent care and advice'
Negative/ wishlist: 'More staff.', 'Staff shortages mean structured day activities can be cancelled at short notice & there is too much time wasted hanging around waiting to see if they run or not.', 'MORE STAFF PLEASE!!!!!!', 'Have less managers doing same job.', ' Staffing levels could improve. More recruitment, nursing assistants especially.', 'Would be good to have cover for support in situations where staff are off for extended periods due to holidays and sickness.', 'I was offered various types of therapy through LMHT but these never happened due to staffing/delays.', 'Get more than one physio and occupational therapist in the team (I have missed out on both). Don't send trainee staff to people in crisis (first person to see me bad).', 'Male members of staff are sometimes explicit in nature, this triggers my PTSD and want to leave. B2`should only have female staff. Staff recruitment spoils what B2 does well.'

:::



::: {.callout-note icon=false title="Staff responsiveness" collapse=true}

### Staff responsiveness

Comments relating to whether staff attend to peoples needs and respond to requests (including call bells) and how timely this is. Includes comments about how busy staff are, and how accommodating they are in responding to requests (the term 'nothing was too much trouble' is frequently used in relation to this).




Examples: 


Positive: 'Staff are always there to help if you need then nothing is ever too much trouble.', 'Staff were kind and available.', 'What was good was the staff tendered to my needs when I was in need.', 'Excellent care - someone comes straIght away when lIght pressed.', 'Someone comes quickly when ring call bell.', 'All of the staff were lovely and if I needed something there was very little wait.', 'All the staff was amazing went above and beyond to help', 'Nothing too much trouble for staff', 'All staff in the ward are atentative, nothing is to much trouble even in more busy periods'
Negative/ wishlist: 'Help me more quickly when I ask.', 'I think that hospital staff don't divulge into patient's quality of care enough i.e. nursing staff should be more responsive.', 'Had to waIt a long tIme for my socks to be put on at tImes.', 'Only mild complaint I had to wait for call bell to be answered at night.', 'Only criticism is sometimes I have to wait for call bell to be answered when wanting to go to the toilet.', 'The staff give the impression that sometimes they are too busy to pay attention to request of relatives.', 'few things not done on time but maybe very busy.', 'staff stood leaning up against the reception desk talking and laughing and not working, not sure why they would do this because some others were running about obviously busy.', 'Answer the buzzer and not keep me waiting when the staff are standing round.', 'All my requests were responded to, although not  always in a timely manner.'

:::



::: {.callout-note icon=false title="Staff continuity" collapse=true}

### Staff continuity

Comments relating to patients seeing/ not seeing the same staff throughout their care, how people feel about this and any issues/ concerns in relation to seeing different staff. It also includes comments relating to how effective staff are in communicating with each other in relation to a patients care, e.g. when handing over.



Examples: 


Positive: 'ConsIstency of nurse has been really helpful.', 'Like getting the same nurse, other nurses are friendly, still…', 'Great communication between staff.'
Negative/ wishlist: 'I would like to see the same nurse all the time.', 'It would have been good to have the same carer so I could get to know them more.', 'Continuity of clinician would be ideal in a therapeutic based treatment.', 'I wasn't listened to at all, passed from person to person and not taken seriously.', 'Continuity of personnel. One consultant identified issues and errors in previous treatment. Disappointment is changing consultants every 12 months. Worry is they change medication as happened once in error.', 'Always seeing different people, continuity would be good. One nurse turned up having not read my notes so she wasn't as helpful as could have been. One doctor had no understanding of some of my problems & couldn't get his head round them.', 'sometimes miscommunication between nurses and doctors', Very poor communication between staff and staff', 'Communication around staff handovers as there has been a lot of repeating myself'

:::



::: {.callout-note icon=false title="Competence & training" collapse=true}

### Competence & training

People's views and experiences relating to whether they are treated by suitably competent, knowledgeable, qualified and trained staff. In includes comments identifying where people feel there are gaps in staff training.



Examples: 


Positive: 'This is a nursing team ably led by [Name], a most empathetic lady who has a superb connection with her patients. The team she leads have obviously been trained to a an extremely high level.', 'Assessment, advice and support from qualified specialist.', 'Felt very reassured by her attItude and knowledge.', 'Excellent sessIon -evIdence based teachIng.', 'Well traIned staff and easy contactable.', ' I felt comfident in the staffs training.'
Negative: 'Hygiene awareness for the staff.', 'A few members of staff could do with more training on compassion, bedside manners and a bit more knowledge on how to handle different types of scenarios.', 'Regarding food I feel staff need more training regarding diabetes.', 'More autism awareness and children with additional needs training needed.', 'You do not put your patients first. You make negligent mistakes. You make detrimental decisions on behalf of patients in the name of best interests when the only interests being served are your own. [Name] was a poor leader and [Name] is only marginally better. The clinical lead nurses are equally awful. There are a few well meaning and hard working nurses but on the whole they are a drop in what is a dysfunctional, unhelpful and chaotic team. They have lost lives and will continue to do so under current management and staffing.'

:::

## TBC

::: {.callout-note icon=false title="Feeling safe" collapse=true}

### Feeling safe

Any comments relating to patients perceptions around how safe they felt/feel. Where stated, the reasons for feeling safe or unsafe, could be numerous (examples include because of the manner of staff, levels of communication, infection control procedures being followed, presence of staff etc.)




Examples: 


Positive: 'I now feel like I have a safety net and fully supported.', 'You kept in touch with me, which make me feel safe. ', 'I think my time spent in here was great, didn't feel unsafe', 'I felt safe and in good hands.', Lovely ward felt safe in the care provided and cared for with respect and dignity.', 'Everyone is so kind and caring it makes you feel safe.', 'Felt safe during COV-19 visiting the hospital.'' l felt so safe here, keep up the good work.', 'The staff were great Really jolly made me feel safe', 'Thank you for looking after me whist I was at [Service name] as I am disabled physically and mentally and walk with a four wheel walker.  I always feel safe when I come here as I am not safe at home and no one to look after me.'

:::



::: {.callout-note icon=false title="Patient appearance & grooming" collapse=true}

### Patient appearance & grooming

Comments which relate to patients being able to dress, groom and present themselves in an acceptable and dignified manner. It includes the availability of clothes and grooming products (e.g. hairbrushes, razors etc.) and how these are made accessible to patients in a timely way.



Examples: 


Positive: 'Nice to have hair done.' 
Negative/ wishlist: 'Took his laundry to be washed but machine broke down with his laundry in it!!. This has been in the machine for days now so he has no clean clothes and walking around with no socks on. I live 17 miles away, I have spoken to nurses who have said several times they would make sure he gets them sorted out today; 3 days later still waiting. Anything he asks for like electric razor, that he has there, he asks several times he will eventually get it.', 'Had to waIt a long tIme for my socks to be put on at tImes.', 'A small mirror would have been nice so I could comb my hair.'

:::



::: {.callout-note icon=false title="Equality, Diversity & Inclusion" collapse=true}

### Equality, Diversity & Inclusion

Comments relating to peoples experiences in relation to age, disability, gender reassignment, marriage and civil partnership, pregnancy and maternity, race, religion or belief, sex or sexual orientation and whether services take into account equality, diversity and inclusion.
NB: Comment relating to issues around disabled parking (number, availability and location of disabled parking bays etc.) should be mapped to 'Parking' rather than here.





Examples: 


Positive: 'Always helpful, polite and adapt to my son's autistic needs.', 'Allowed for m old age problems.', 'Staff understand my disability and help me.', 'Fully support of my needs as I am disabled.', 'I am a transgender woman and everybody track me like I am a proper woman that was so lovely and professional', 'the service as a whole is very accessible and accommodating to me as someone with autism and ADHD.' 
Negative/ wishlist: 'Help people to integrate into their own culture.  Difficult if first language isn't English.  People from different heritage or background may find it difficult.', 'I am disable person in a wheelchair, and couldn't get any help to access the hospital.', 'Be more aware of people who like me score very high on the Autistic Spectrum but do not have learning difficulties - the old version of Asperger's.', 'More understanding for people with learning disabilities.', 'It could be helpful to have deaf awareness maybe minicom for booking / cancellations and staff having BSL basic to converse with deaf patients.', 'Like if your a transgender more help needed. No information on Transgender or tablets need if your transgender, more help needed.', 'I suffer from M.S and am severely disabled - need more help with feeding.'

:::

